# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SmTd8Hqgm7FkSjcmT5x94NM47Vfu_OaS
"""

def televizor_narxi(marka):
    if marka == "Samsung":
        return "Narxi: $500 - $1500 (modelga qarab)"
    elif marka == "LG":
        return "Narxi: $400 - $1400 (model va o‘lchamga qarab)"
    elif marka == "Sony":
        return "Narxi: $700 - $2000 (Bravia modellari uchun)"
    elif marka == "TCL":
        return "Narxi: $300 - $800 (arzon variantlar uchun)"
    elif marka == "Philips":
        return "Narxi: $450 - $1200 (texnologiyasi bilan)"
    elif marka == "Hisense":
        return "Narxi: $250 - $900 (byudjet variantlari uchun)"
    elif marka == "Panasonic":
        return "Narxi: $600 - $1300 (premium modellari uchun)"
    elif marka == "Sharp":
        return "Narxi: $350 - $1000 (LED va 4K modellari uchun)"
    elif marka == "Vizio":
        return "Narxi: $400 - $1100 (OLED yoki QLED uchun)"
    elif marka == "Xiaomi":
        return "Narxi: $300 - $700 (arzon 4K televizorlar)"
    else:
        return "Bu marka bo‘yicha ma'lumot yo'q, boshqa markani kiriting."

marka = input("Televizor markasini kiriting: ")
natija = televizor_narxi(marka)
print(natija)